HRSystem/Web/Controllers/AdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.OutputCaching;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using static HRSystem.Domain.Enums;
using Microsoft.AspNetCore.Authorization;
using HRSystem.Domain.Entities;
using HRSystem.Infrastructure.Repositories;
using HRSystem.Application.ViewModels;
using HRSystem.Application.Dtos;

namespace HRSystem.Web.Controllers;

[Authorize]
[OutputCache(PolicyName = "OutputCacheWithVaryByQuery")]
public class ContractController : Controller
{
    private readonly ILogger<ContractController> _logger;
    private readonly IContractRepository _contractRepository;
    private readonly IStaffRepository _staffRepository;
    private readonly IMapper _mapper;

    [TempData]
    public string? _dialog { get; set; }

    public ContractController(
        ILogger<ContractController> logger,
        IContractRepository contractRepository,
        IStaffRepository staffRepository,
        IMapper mapper)
    {
        _logger = logger;
        _contractRepository = contractRepository;
        _staffRepository = staffRepository;
        _mapper = mapper;
    }

    [OutputCache(Duration = 60)]
    public async Task<IActionResult> Index(string searchString = "", int page = 1)
    {
        DialogViewModel? dialogViewModel = !string.IsNullOrEmpty(_dialog)
            ? JsonSerializer.Deserialize<DialogViewModel>(_dialog)
            : null;

        var query = (await _contractRepository.GetAllAsync()).AsQueryable();

        if (!string.IsNullOrEmpty(searchString))
        {
            query = query.Where(c => c.StaffNo.ToString().Contains(searchString) || c.Position.Contains(searchString));
        }
        var contracts = query.Skip((page - 1) * 10).Take(10);

        var data = _mapper.Map<IEnumerable<ContractViewModel>>(contracts);
        var tuple = (data, dialogViewModel);
        return View(tuple);
    }

    public async Task<IActionResult> Details(int id)
    {
        var contract = await _contractRepository.GetByIdAsync(id);
        if (contract == null) return NotFound();

        var viewModel = _mapper.Map<ContractViewModel>(contract);
        return View(viewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Create(int id)
    {
        var viewModel = new ContractViewModel
        {
            StaffNo = id,
            Status = Status.Draft,
            ListStaffNo = new SelectList(await _staffRepository.GetAllAsync(), "StaffNo", "StaffNo", id)
        };

        return View(viewModel);
    }


    [HttpPost, ActionName("Create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ContractDto viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View("Create", viewModel);
        }

        try
        {
            var contract = _mapper.Map<Contract>(viewModel);
            contract.Id = null;
            await _contractRepository.AddAsync(contract);
            await _contractRepository.SaveChangesAsync();
            _logger.LogInformation($"Created contract {contract.ContractNumber}");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.primary, message = $"Created contract {contract.ContractNumber}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating contract");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.danger, message = $"Error:\n\n{ex.InnerException}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
            viewModel.ListStaffNo = new SelectList(await _staffRepository.GetAllAsync(), "StaffNo", "StaffNo", viewModel.StaffNo);
            return View("Create", viewModel);
        }
    }

    public async Task<IActionResult> Edit(int id)
    {
        var contract = await _contractRepository.GetByIdAsync(id);
        if (contract == null) return NotFound();

        var viewModel = _mapper.Map<ContractViewModel>(contract);
        viewModel.ListStaffNo = new SelectList(await _staffRepository.GetAllAsync(), "StaffNo", "StaffNo", viewModel.StaffNo);
        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, ContractDto viewModel)
    {
        if (id != viewModel.Id) return NotFound();
        ModelState.Remove("StartDate");
        if (!ModelState.IsValid)
        {
            viewModel.ListStaffNo = new SelectList(await _staffRepository.GetAllAsync(), "StaffNo", "StaffNo", viewModel.StaffNo);
            return View("Edit", viewModel);
        }

        try
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            if (contract == null) return NotFound();

            _mapper.Map(viewModel, contract);
            await _contractRepository.UpdateAsync(contract);
            await _contractRepository.SaveChangesAsync();
            var dialogViewModel = new DialogViewModel { dialog = Dialog.primary, message = $"Edited contract {contract.ContractNumber}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
            return RedirectToAction(nameof(Index));
        }
        catch (DbUpdateConcurrencyException)
        {
            if (await _contractRepository.GetByIdAsync(viewModel.Id) == null) return NotFound();
            throw;
        }
    }

    public async Task<IActionResult> Delete(int id)
    {
        var contract = await _contractRepository.GetByIdAsync(id);
        if (contract == null) return NotFound();

        var viewModel = _mapper.Map<ContractViewModel>(contract);
        return View(viewModel);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        try
        {
            var contract = await _contractRepository.GetByIdAsync(id);
            if (contract == null) return NotFound();

            await _contractRepository.DeleteAsync(id);
            await _contractRepository.SaveChangesAsync();
            var dialogViewModel = new DialogViewModel { dialog = Dialog.primary, message = $"Deleted contract {contract.ContractNumber}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting contract");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.danger, message = $"Error:\n\n{ex.InnerException}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
        }
        return RedirectToAction(nameof(Index));
    }
}

HRSystem/Web/Controllers/StaffController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using static HRSystem.Domain.Enums;
using Microsoft.AspNetCore.Authorization;
using HRSystem.Domain.Entities;
using HRSystem.Infrastructure.Repositories;
using HRSystem.Application.ViewModels;

namespace HRSystem.Web.Controllers;

[Authorize]
public class StaffController : Controller
{
    private readonly ILogger<StaffController> _logger;
    private readonly IStaffRepository _staffRepository;
    private readonly IMapper _mapper;

    [TempData]
    public string? _dialog { get; set; }

    public StaffController(
        ILogger<StaffController> logger,
        IStaffRepository staffRepository,
        IMapper mapper)
    {
        _logger = logger;
        _staffRepository = staffRepository;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index()
    {
        DialogViewModel? dialogViewModel = !string.IsNullOrEmpty(_dialog)
            ? JsonSerializer.Deserialize<DialogViewModel>(_dialog)
            : null;

        var staff = await _staffRepository.GetAllAsync();
        var data = _mapper.Map<IEnumerable<StaffViewModel>>(staff);
        var tuple = (data, dialogViewModel);
        return View(tuple);
    }

    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();

        var staff = await _staffRepository.GetByIdAsync(id.Value);
        if (staff == null) return NotFound();

        var viewModel = _mapper.Map<StaffViewModel>(staff);
        return View(viewModel);
    }

    public IActionResult Create() => View();

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(StaffViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        try
        {
            var staff = _mapper.Map<Staff>(viewModel);
            await _staffRepository.AddAsync(staff);
            await _staffRepository.SaveChangesAsync();
            _logger.LogInformation($"Created staff {staff.StaffNo}");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.primary, message = $"Created staff {staff.StaffNo}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating staff");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.danger, message = $"Error:\n\n{ex.InnerException}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
            return View(viewModel);
        }
    }

    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null) return NotFound();

        var staff = await _staffRepository.GetByIdAsync(id.Value);
        if (staff == null) return NotFound();

        var viewModel = _mapper.Map<StaffViewModel>(staff);
        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, StaffViewModel viewModel)
    {
        if (id != viewModel.StaffNo) return NotFound();
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        try
        {
            var staff = await _staffRepository.GetByIdAsync(id);
            if (staff == null) return NotFound();

            _mapper.Map(viewModel, staff);
            await _staffRepository.UpdateAsync(staff);
            await _staffRepository.SaveChangesAsync();
            _logger.LogInformation($"Edited staff {id}");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.primary, message = $"Edited staff {staff.StaffNo}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error editing staff");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.danger, message = $"Error:\n\n{ex.InnerException}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
            return View(viewModel);
        }
    }

    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null) return NotFound();

        var staff = await _staffRepository.GetByIdAsync(id.Value);
        if (staff == null) return NotFound();

        var viewModel = _mapper.Map<StaffViewModel>(staff);
        return View(viewModel);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        try
        {
            var staff = await _staffRepository.GetByIdAsync(id);
            if (staff == null) return NotFound();

            await _staffRepository.DeleteAsync(id);
            await _staffRepository.SaveChangesAsync();
            _logger.LogInformation($"Deleted staff {staff.StaffNo}");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.primary, message = $"Deleted staff {staff.StaffNo}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting staff");
            var dialogViewModel = new DialogViewModel { dialog = Dialog.danger, message = $"Error:\n\n{ex.InnerException}" };
            _dialog = JsonSerializer.Serialize(dialogViewModel);
        }
        return RedirectToAction(nameof(Index));
    }
}

HRSystem/Web/Views/Staff/Create.cshtml
@model StaffViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Staff</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StaffName" class="control-label"></label>
                <input asp-for="StaffName" class="form-control" />
                <span asp-validation-for="StaffName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate"></label>
                <input asp-for="BirthDate" class="form-control" type="date" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address1" class="control-label"></label>
                <input asp-for="Address1" class="form-control" />
                <span asp-validation-for="Address1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address2" class="control-label"></label>
                <input asp-for="Address2" class="form-control" />
                <span asp-validation-for="Address2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address3" class="control-label"></label>
                <input asp-for="Address3" class="form-control" />
                <span asp-validation-for="Address3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address4" class="control-label"></label>
                <input asp-for="Address4" class="form-control" />
                <span asp-validation-for="Address4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HRSystem/Web/Views/Staff/Delete.cshtml
@model StaffViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Staff</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StaffName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StaffName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address1)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address3)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address3)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address4)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StaffNo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HRSystem/Web/Views/Staff/Details.cshtml
@model StaffViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Staff</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StaffNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StaffNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StaffName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StaffName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address1)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address1)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address3)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address3)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address4)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.StaffNo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HRSystem/Web/Views/Staff/Edit.cshtml
@model StaffViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Staff</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="StaffNo" class="form-control" readonly />
            <div class="form-group">
                <label asp-for="StaffName" class="control-label"></label>
                <input asp-for="StaffName" class="form-control" />
                <span asp-validation-for="StaffName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate"></label>
                <input asp-for="BirthDate" class="form-control" type="date" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address1" class="control-label"></label>
                <input asp-for="Address1" class="form-control" />
                <span asp-validation-for="Address1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address2" class="control-label"></label>
                <input asp-for="Address2" class="form-control" />
                <span asp-validation-for="Address2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address3" class="control-label"></label>
                <input asp-for="Address3" class="form-control" />
                <span asp-validation-for="Address3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address4" class="control-label"></label>
                <input asp-for="Address4" class="form-control" />
                <span asp-validation-for="Address4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HRSystem/Web/Views/Staff/Index.cshtml
@using HRSystem.Application.ViewModels;
@model (IEnumerable<StaffViewModel> svm, DialogViewModel dvm)

@{
    ViewData["Title"] = "Index";
    var sample = Model.svm?.FirstOrDefault() ?? new StaffViewModel();
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(_ => sample.StaffNo)</th>
            <th>@Html.DisplayNameFor(_ => sample.StaffName)</th>
            <th>@Html.DisplayNameFor(_ => sample.BirthDate)</th>
            <th>@Html.DisplayNameFor(_ => sample.Address1)</th>
            <th>@Html.DisplayNameFor(_ => sample.Address2)</th>
            <th>@Html.DisplayNameFor(_ => sample.Address3)</th>
            <th>@Html.DisplayNameFor(_ => sample.Address4)</th>
            <th>@Html.DisplayNameFor(_ => sample.EmailAddress)</th>
            <th>@Html.DisplayNameFor(_ => sample.PhoneNumber)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.svm != null && Model.svm.Any())
        {
            foreach (var item in Model.svm)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.StaffNo)</td>
                    <td>@Html.DisplayFor(modelItem => item.StaffName)</td>
                    <td>@Html.DisplayFor(modelItem => item.BirthDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address1)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address2)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address3)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address4)</td>
                    <td>@Html.DisplayFor(modelItem => item.EmailAddress)</td>
                    <td>@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.StaffNo">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.StaffNo">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.StaffNo">Delete</a> |
                        <a asp-controller="Contract" asp-action="Create" asp-route-id="@item.StaffNo">Create Contract</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="10" class="text-center text-muted">No staff records found.</td>
            </tr>
        }
    </tbody>
</table>

@await Html.PartialAsync("Dialog", Model.dvm)